### ISSUE TITLE
.NET 6 not working

### ISSUE THREAD

**Issue by rudolph2907** [ExtCore/ExtCore-Sample-Identity#2]
Hi

I am looking to try this out, but get an 500 error after rebuild and running:
```
Connection id "0HMGU56Q37R36", Request id "0HMGU56Q37R36:00000002": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
      /Views/Default/Index.cshtml
      /Views/Shared/Index.cshtml
      /Pages/Shared/Index.cshtml
         at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
```

Even though I've made sure that the files does exists and is being marked as Always copy.

**Comment by rudolph2907** [comment]
Nevermind, I've tried it on a different machine and it was working normally. So must be an dependency on the machine.
